# Generated by Django 5.0.6 on 2024-07-16 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_remove_student_student_number_student_result_and_more'),
    ]

    operations = [
    ]
